-- CREATE A WAREHOUSE
CREATE WAREHOUSE REDFINWH;

-- CREATE AND USE A DATABASE
CREATE OR REPLACE DATABASE REDFIN_DB;
USE REDFIN_DB;

-- CREATE A SCHEMA
CREATE OR REPLACE SCHEMA REDFIN_SCHEMA;

-- CREATE A CSV FILE FORMAT
CREATE OR REPLACE FILE FORMAT REDFIN_SCHEMA.CSV_FILE_FORMAT
    TYPE = CSV 
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'NULL')
    EMPTY_FIELD_AS_NULL = TRUE;

-- CREATE A STAGE
CREATE OR REPLACE STAGE REDFIN_SCHEMA.REDFIN_STAGE
    URL='--BUCKET URL--'
    CREDENTIALS=(AWS_KEY_ID='XXX' AWS_SECRET_KEY='XXX')
    FILE_FORMAT=REDFIN_SCHEMA.CSV_FILE_FORMAT;

-- CREATE TABLES
CREATE OR REPLACE TABLE REDFIN_DB.REDFIN_SCHEMA.REDFIN_TABLE (
PERIOD_BEGIN DATE,
PERIOD_END DATE,
PERIOD_DURATION INT,
REGION_TYPE STRING,
REGION_TYPE_ID INT,
TABLE_ID INT,
IS_SEASONALLY_ADJUSTED STRING,
CITY STRING,
STATE STRING,
STATE_CODE STRING,
PROPERTY_TYPE STRING,
PROPERTY_TYPE_ID INT,
MEDIAN_SALE_PRICE FLOAT,
MEDIAN_LIST_PRICE FLOAT,
MEDIAN_PPSF FLOAT,
MEDIAN_LIST_PPSF FLOAT,
HOMES_SOLD FLOAT,
INVENTORY FLOAT,
MONTHS_OF_SUPPLY FLOAT,
MEDIAN_DOM FLOAT,
AVG_SALE_TO_LIST FLOAT,
SOLD_ABOVE_LIST FLOAT,
PARENT_METRO_REGION_METRO_CODE STRING,
LAST_UPDATED DATETIME,
PERIOD_BEGIN_IN_YEARS STRING,
PERIOD_END_IN_YEARS STRING,
PERIOD_BEGIN_IN_MONTHS STRING,
PERIOD_END_IN_MONTHS STRING
);


-- CREATE PIPES WITH PATTERN ATTRIBUTE TO MATCH SPECIFIC FILE TYPES
CREATE OR REPLACE PIPE REDFIN_SCHEMA.REDFIN_PIPE 
AUTO_INGEST = TRUE 
AS 
COPY INTO REDFIN_SCHEMA.REDFIN_TABLE
    FROM @REDFIN_SCHEMA.REDFIN_STAGE
    FILE_FORMAT = REDFIN_SCHEMA.CSV_FILE_FORMAT
    PATTERN = '.*REDFIN_PIPE.*\\.CSV';

-- SELECT DATA FROM TABLES TO VERIFY INGESTION
SELECT * FROM REDFIN_DB.REDFIN_SCHEMA.REDFIN_TABLE;
